/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './Education.module.css'


export default function Education() {
  return (
    <>
      <Head>
        <title>教育经历</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"/"}>
          <div className={styles.footer}>
            <div className={styles.next}>
              <Image src="/up.svg" alt='向上继续' width={40} height={40} priority/>
              <h3 >
                个人简介
              </h3>
            </div>
          </div> 
        </Link>

        <div className={styles.center}>
          <div className={styles.up}>
            <img className={styles.image} src="kmlg.png" alt="" />
            <div className={styles.text}>
              <span>昆明理工大学 <i>2017.09-2021.07</i> </span>
              <h5>计算机科学与技术 | 本科</h5>
              <ul>
                <li>xxx</li>
                <li>xxx</li>
              </ul>
            </div>
          </div>
          <div className={styles.down}>
            <div className={styles.text}>
              <span>重庆邮电大学 <i>2021.09-2024.06</i> </span>
              <h5>计算机技术 | 硕士</h5>
              <ul>
                <li>xxx</li>
                <li>xxx</li>
              </ul>
            </div>
            <img className={styles.image} src="cqyd.png" alt="" />
          </div>
          
        </div>

        <Link href={"skill"}>
          <div className={styles.footer}>
            <div className={styles.next}>
              <h3>
                专业技能
              </h3>
              <Image src="/next.svg" alt='向下继续' width={40} height={40} priority/>
            </div>
          </div> 
        </Link>
      </main>
    </>
  )
}
