/* eslint-disable @next/next/no-img-element */
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './Education.module.css'


export default function Education(props:any) {
  const { education } = props
  return (
    <>
      <Head>
        <title>教育经历</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"/"}>
          <div className={styles.footer}>
            <div className={styles.back}>
              <Image src="/up.svg" alt='向上继续' width={40} height={40} priority/>
              <h3 >
                个人简介
              </h3>
            </div>
          </div> 
        </Link>

        <div className={styles.center}>
          {
            education.length ? 
            education.map((item: any,index: any) => {
              return (
                <div key={index} className={ styles.content }>
                  <div className={styles.image}><Image src={item.imgUrl} alt='向上继续' fill priority/></div>
                  {/* <Image className={styles.image} src={item.imgUrl} alt='向上继续' width={40} height={40} priority/> */}
                  {/* <img className={styles.image} src={item.imgUrl} alt="" /> */}
                  <div className={styles.text}>
                    <span>{item.name} <i>{item.start}-{item.end}</i> </span>
                    <h5>{item.major} | {item.degree}</h5>
                    <ul>
                      {
                        item.glory.map((item: any, index: any) => {
                          return <li key={index}>{item}</li>
                        })
                      }
                    </ul>
                  </div>
                </div>
                )
            }) : null
          }      
        </div>

        <Link href={"skill"}>
          <div className={styles.footer}>
            <div className={styles.next}>
              <h3>
                专业技能
              </h3>
              <Image src="/next.svg" alt='向下继续' width={40} height={40} priority/>
            </div>
          </div> 
        </Link>
      </main>
    </>
  )
}

export async function getStaticProps(){
  const education = await axios.get('http://47.115.201.17:8081/api/education').then((res) => {
    console.log(res.data)
    return res.data.data
  })
  return {
    props:{
      education
    }
  }
}
