/* eslint-disable @next/next/no-img-element */
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './Skill.module.css'


export default function Skill(props:any) {
  console.log(props)
  return (
    <>
      <Head>
        <title>专业技能</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"education"}>
          <div className={styles.footer}>
            <div className={styles.up}>
              <Image src="/up.svg" alt='向上继续' width={40} height={40} priority/>
              <h3 >
                教育经历
              </h3>
            </div>
          </div> 
        </Link>

        <div className={styles.center}>
          {/* <h1>中间部分</h1> */}
          <div className={styles.familiar}>
            <ul>
              <li > 
                <Image src="/skill/css.svg" alt='' width={40} height={40} priority />
                <span>熟练使用css</span>
              </li>
              <li>
                <Image src="/skill/html.svg" alt='' width={40} height={40} priority />
              </li>
              <li>
                <Image src="/skill/js.svg" alt='' width={40} height={40} priority />
              </li>
              <li>
                <Image src="/skill/react.svg" alt='' width={40} height={40} priority />
              </li>
              <li>
                <Image src="/skill/http.svg" alt='' width={40} height={40} priority />
              </li>
              <li>
                <Image src="/skill/git.svg" alt='' width={40} height={40} priority />
              </li>
            </ul>
          </div>
          <div className={styles.understand}>
            <ul>
              <li>
                <Image src="/skill/vue.svg" alt='' width={40} height={40} priority />
              </li>
              <li>
                <Image src="/skill/node.svg" alt='' width={40} height={40} priority />
              </li>
            </ul>
          </div>
        </div>

        <Link href={"project"}>
          <div className={styles.footer}>
            <div className={styles.next}>
              <h3>
                项目经历
              </h3>
              <Image src="/next.svg" alt='向下继续' width={40} height={40} priority/>
            </div>
          </div> 
        </Link>
      </main>
    </>
  )
}
