/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props:any) {

  const { info } = props

  return (
    <>
      <Head>
        <title>阮杭生的个人简历</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>
            个  人  简  介 
          </h1>
        </div>

        <div className={styles.center}>
          <div className={styles.avatar}>
            <img className={styles.logo} src="/avatar.jpg" alt="证件照"  />
          </div>
          
          <div className={styles.intro}>
            <ul >
              <li><h3>{info.name}-{info.position}</h3> </li>
              <li>{`${info.age} | ${info.sex} | ${info.origin} | ${info.politics}`}</li>
              <li>
                <Image src="/dianhua.svg" alt='电话' width={13} height={13} priority/>
                {` ${info.phone}`};
              </li>
              <li>
                <Image src="/email.svg" alt='邮箱' width={13} height={13} priority/>
                {` ${info.email}`}
              </li>
              <li>
                <Image src="/weixin.svg" alt='微信' width={13} height={13} priority/>
                {` ${info.wechat}`}
              </li>
              <li>{info.text}</li>
            </ul>
          </div>
        </div>

        <Link href={"education"}>
          <div className={styles.footer}>
            <div className={styles.next}>
              <h3 >
                教育经历
              </h3>
              <Image src="/next.svg" alt='向下继续' width={40} height={40} priority/>
            </div>
          </div> 
        </Link>
      </main>
    </>
  )
}

export async function getServerSideProps() {


  // const res = await fetch("https://dummyjson.com/products")
  // const resJson = await res.json()
  const info = await axios.get("http://localhost:3000/api/home").then((res) => {
    return res.data
  })
  return {
    props:{
      info
    }
  }
  
}