/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from './Project.module.css'


export default function Skill() {
  return (
    <>
      <Head>
        <title>专业技能</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={"education"}>
          <div className={styles.header}>
            <div className={styles.next}>
              <Image src="/up.svg" alt='向上继续' width={40} height={40} priority/>
              <h3 >
                教育经历
              </h3>
            </div>
          </div> 
        </Link>

        <div className={styles.center}>
          <h1>中间部分</h1>
        </div>

        <div className={styles.footer}>
          <h1>
            感谢观看
          </h1>
        </div> 
      </main>
    </>
  )
}
